### ISSUE TITLE
Installed the younow-Tools npm get no such file error

### ISSUE THREAD

**Issue by Ugur22** [UnCrevard/Younow-Tools#1]
I have installed the younow-Tools npm but when I try to start it it keeps giving me this error:
/usr/bin/env: ‘node\r’: No such file or directory

I'm on linux by the way. would you guys know why i'm getting this error?

**Comment by UnCrevard** [comment]
update younow-tools or edit younow.js/main.js to remove the 1st line #!/usr/bin/env node.

Sorry. Nice to have feedback on linux btw.

**Comment by Ugur22** [comment]
thanks for the reply. that error is now fixed after updating it but now I'm getting these errors:

/usr/local/bin/younow: line 1: use strict: command not found
/usr/local/bin/younow: line 1: $'\r': command not found
/usr/local/bin/younow: line 2: syntax error near unexpected token `('
/usr/local/bin/younow: line 2: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, gener'tor) {

**Comment by UnCrevard** [comment]
The file is run by bash not with nodejs. I don't know why.

try this :

# uninstall globally
npm -g uninstall younow-tools

# install younow-tools in the current dir
npm install younow-tools

# run the api command for example
node node_modules/younow-tools/js/main.js -v api

it's ugly but it should works.

**Comment by Ugur22** [comment]
thanks that worked :)

**Comment by Ugur22** [comment]
I have one last question so younow-Tools is working now and I added 2 users to the database. 
If I want to track these 2 users and record their broadcast when they're going live I would need the following command line right?
node node_modules/younow-tools/js/main.js scan -t 5 script.js

and my script file has the following code:
`function main() {
log("init scanning...")
     if (user) {
            return "follow";
            log("follow");
        else {
            return "waiting";
           log("waiting");
        }
    }
}
try {
    main();
}
catch (e) {
    e;
}
`

**Comment by UnCrevard** [comment]
// **Broadcasters in the database are always recorded.**
// So this script ignore everybody else

```
if (tag)
{
true // all tags
}
else
{
"ignore"
}
```

**Comment by Ugur22** [comment]
oke thanks I will try out

**Comment by Ugur22** [comment]
But without the scan command it wont record the live broadcasts right of the users in the DB?
and does the VCR command download the last 10 broadcasts of a user?

**Comment by UnCrevard** [comment]
Live notification is only available on the website. So the scan command is needed to monitor lives and check if a user in the db is broadcasting. it just loads the list of current broadcasters. It's lite and fast.

The vcr command is looking for user moments (not always enabled) and download all the broadcasts if they're not already in the download folder.

By the way, younow-tools now works fine on linux now. Just type npm -g install younow-tools and the younow command will be available and works :D

**Comment by Ugur22** [comment]
Okey thanks the younow command works now. But my scan command didnt seem to work. last night one of my users went live but it did not record the broadcast. this is my script:
`function main() {
log("init scanning...")
 if (tag)
{
true // all tags
}
else
{
"ignore"
}
}
try {
    main();
}
catch (e) {
    e;
}
`

and I used this command: younow scan script.js

**Comment by UnCrevard** [comment]
It should work. User in the db have priority.

First check users are in your database :

    younow search "userid"

An alternative way to do it is :
```
if (tag)
{
    true
}
else if (user)
{
    if (user.profile=="username" || user.userId==12345)
    {
        log(user.profile,"is online !!!!")
          "follow"
    }
}
```

add -v to younow to have debug information and see what's happening.

Hope it helps.

**Comment by Ugur22** [comment]
I added iv to the command and it gives me this: 

> 	version: 1.0.20
	pathDB: /home/ugur/YounowTools/broadcasters.txt
	pathDownload: .
	pathMove: null
	dbBroadcasters: null
	pathConfig: /home/ugur/YounowTools
	parallelDownloads: 5
	useFFMPEG: false
	FFMPEG_DEFAULT: -hide_banner -loglevel error -c copy -video_track_timescale 0
	videoFormat: ts
	args: null

scan interval 300

its weird that dbBroadcasters: null because I have 4 users in my db.

**Comment by UnCrevard** [comment]
Il always null. No purpose.

But you need to run younow scan with -v so you will see what younow is doing.

If a user appears on the website under any tag it's will be catch by the scan command.

Even with no viewer or a custom tag.

Or there is a problem and younow doesn't expose all the users online.

I am looking at it.

**Comment by UnCrevard** [comment]
I added a new option to change the locale used on younow. By default it uses english.

`--locale <xx> change the default (en) locale (ww|en|de|es|tr|me)`

**Comment by Ugur22** [comment]
I used the -v command and tried out a user that was live at the moment still didnt work. so maybe younow is indeed not exposing all the users

**Comment by Ugur22** [comment]
to change the locale to ww I need to enter the following right: younow  --locale ww?

**Comment by UnCrevard** [comment]
yes the results are differentes.
