### ISSUE TITLE
Any way to drop the 'Younow_' from filenames?

### ISSUE THREAD

**Issue by donradzsk** [UnCrevard/Younow-Tools#10]
I liked how it was before with filenames starting with the country codes.

**Comment by UnCrevard** [comment]
Use the --filename switch before the command to change the format : 

younow --filename country_username_date_type_bid  {cmd} {params}

**Comment by donradzsk** [comment]
Thanks. Can we add the channel ID also?

**Comment by UnCrevard** [comment]
no only service country username date type broadcastId are available.

**Comment by mjolnir870** [comment]
Can you please add "status" to the available variables for the filename? I can see that "status" is recorded in the json file and I see it in the console output as videos are downloaded, but it's not available in the filename.

**Comment by UnCrevard** [comment]
There is no status property in json files. It's from follow or scan command ?

**Comment by mjolnir870** [comment]
I downloaded from a periscope user using this command
`younow --periscope vcr imiguelzazueta`
In the periscope.json file in my AppData, the following entry is made:
`+1zqKVazDBQVxB:{"class_name":"Broadcast","id":"1zqKVazDBQVxB","created_at":"2019-05-26T18:58:47.623313076Z","updated_at":"2019-05-26T19:15:49.926069326Z","user_id":"14179298","user_display_name":"imiguelzazueta","username":"imiguelzazueta","twitter_id":"69572573","twitter_username":"iMiguelZazueta","profile_image_url":"https://prod-profile.pscp.tv/14179298/a2f1f2cecabeec2d8a48f79ca1f0a9dd-128.jpg","state":"ENDED","is_locked":false,"friend_chat":false,"private_chat":false,"language":"es","version":125,"start":"2019-05-26T18:59:13.738058434Z","ping":"2019-05-26T19:15:43.960485879Z","end":"2019-05-26T19:15:48.102718071Z","has_moderation":true,"has_location":false,"city":"","country":"","country_state":"","iso_code":"","ip_lat":0,"ip_lng":0,"width":320,"height":568,"camera_rotation":0,"image_url":"https://prod-video-us-west-2.pscp.tv/P-_HqIMfTLytmZWgB8nirG5QNYi6D7wNura9E6ICspxhO_hd4CjiY_v77Rkh-0L7-ZZKRooG1ujFFmc0OojohA/replay_thumbnail/us-west-2/periscope-replay-direct-prod-us-west-2-public/eyJkIjowfQ/chunk_1558898139529686066_310_a.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbInRodW1iIl0sIkJyb2FkY2FzdElkIjoiMXpxS1ZhekRCUVZ4QiIsIkdyYW50VHlwZSI6InJlYWQiLCJHcmFudGVkQXQiOjE1NTkwNzAxOTcsIkdyYW50ZWRUbyI6IndlYi01YTcyNjc4YS01NTYxLTQ3MDYtNDkzNC1hNDc2Njc1MzM1NGYiLCJTdHJlYW1OYW1lIjoiUC1fSHFJTWZUTHl0bVpXZ0I4bmlyRzVRTllpNkQ3d051cmE5RTZJQ3NweGhPX2hkNENqaVlfdjc3UmtoLTBMNy1aWktSb29HMXVqRkZtYzBPb2pvaEEiLCJleHAiOjE1NTkyNDI5OTd9.uyj9hYf-KzB_lDvjG3Gn7TRo-X-Xmx2Fmpgvc2D7lzo&service=proxsee&digest=VfcsBEVEw6C50Tju9dbyOFfWiX24GamsPTxppk93x2I","image_url_small":"https://prod-video-us-west-2.pscp.tv/P-_HqIMfTLytmZWgB8nirG5QNYi6D7wNura9E6ICspxhO_hd4CjiY_v77Rkh-0L7-ZZKRooG1ujFFmc0OojohA/replay_thumbnail/us-west-2/periscope-replay-direct-prod-us-west-2-public/eyJkIjoxMjh9/chunk_1558898139529686066_310_a.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbInRodW1iIl0sIkJyb2FkY2FzdElkIjoiMXpxS1ZhekRCUVZ4QiIsIkdyYW50VHlwZSI6InJlYWQiLCJHcmFudGVkQXQiOjE1NTkwNzAxOTcsIkdyYW50ZWRUbyI6IndlYi01YTcyNjc4YS01NTYxLTQ3MDYtNDkzNC1hNDc2Njc1MzM1NGYiLCJTdHJlYW1OYW1lIjoiUC1fSHFJTWZUTHl0bVpXZ0I4bmlyRzVRTllpNkQ3d051cmE5RTZJQ3NweGhPX2hkNENqaVlfdjc3UmtoLTBMNy1aWktSb29HMXVqRkZtYzBPb2pvaEEiLCJleHAiOjE1NTkyNDI5OTd9.uyj9hYf-KzB_lDvjG3Gn7TRo-X-Xmx2Fmpgvc2D7lzo&service=proxsee&digest=VfcsBEVEw6C50Tju9dbyOFfWiX24GamsPTxppk93x2I","status":"Domingo familiar Nogales Sónora","content_type":"video","broadcast_source":"bluebird_ios_7.50","available_for_replay":true,"expiration":-1,"tweet_id":"1132722879995437056","tweet_external":true,"media_key":"28_1132722768733040640"}`

At the end you can see `"status":"Domingo familiar Nogales Sónora"` recorded.

**Comment by UnCrevard** [comment]
on periscope the status is just the title of the broadcast.
to format the filename just add to any command :

--filename service_country_username_date_title_type_bid

on younow there is no title that's why/

**Comment by mjolnir870** [comment]
Thanks, that worked.
