### ISSUE TITLE
Replay no longer exists? does this still work?

### ISSUE THREAD

**Issue by frowtown** [UnCrevard/Younow-Tools#11]
after typing in younow vcr username it says it's extracting broadcasts but then it comes up in red saying 
(username) 161262005 263 replay no longer exists 
a bunch of times. the first string of numbers changes for each one but the 263 is always there.
and for some users it just says
current broadcast extracted: 0
is there any way around this or am i totally screwed?

**Comment by chickenmango1** [comment]
yeah having the same issue.

**Comment by UnCrevard** [comment]
Younow only archives main broadcasters for longer time. Other it's just a week.
