### ISSUE TITLE
Status:BROADCASTING

### ISSUE THREAD

**Issue by donradzsk** [UnCrevard/Younow-Tools#15]
Have they made any recent changes? All I'm seeing is
```
Status:BROADCASTING
Status:ONLINE
Status:BROADCASTING
Status:BROADCASTING
Status:BROADCASTING
```

**Comment by donradzsk** [comment]
Yes
`younow --filename country_username_date_bid -t 1 --dl "M:\VIDEO\YNTool\" follow myusername`

**Comment by UnCrevard** [comment]
yes I need to update the code something has changed.

**Comment by UnCrevard** [comment]
fixed

**Comment by donradzsk** [comment]
It worked for a while but now it's back to Status:ONLINE.

**Comment by UnCrevard** [comment]
Forgot the online status. Not a big deal. Broadcasting is working as usual. Next update will fix that.
