### ISSUE TITLE
Help with Scan command

### ISSUE THREAD

**Issue by Testing2134** [UnCrevard/Younow-Tools#16]
Could you explain the "scan" command to me? From reading the documentation it's supposed to read the database file and automatically download broadcasts from those users. When attempting to use the scan command I receive the error "missing required argument `config_file'". 

When trying to point it at the broadcasters file I then get "SyntaxError: Invalid or unexpected token" which leads me to think I don't understand the usage of this command.

**Comment by UnCrevard** [comment]
the scan command needs a javascript script to filter online user.
the syntax is

younow scan script.js

there is 2 scripts example https://github.com/UnCrevard/Younow-Tools/blob/master/script_example1.ts

**Comment by Testing2134** [comment]
Hmm okay I understand a bit more and attempted to modify your scripts to get them to function the way I wanted but I know next to nothing about javascript. Could you write me a small script that I could plug userid and usernames into to have them autodownload?

I attempted to use the "follow" command on my own profile but it seems to be very inconsistent and is missing a lot of broadcasts.

**Comment by UnCrevard** [comment]
the follow command starts recording at the end of the broadcast.

**Comment by Testing2134** [comment]
This is the part of the scan command that I dont understand 

Add broadcaster(s) to your local database
for faster resolve
database query
**record their live broadcasts (scan mode)**

After adding a user to the local database how do I then use the scan command to record their broadcasts?

**Comment by UnCrevard** [comment]
the best way is to use the follow command to scan the broadcasters on your profile list.

the scan command is more useful for scan ALL broadcaster then filter them.

**Comment by spinningsand** [comment]
Is there a way to filter users with the follow command so it only downloads broadcasts from certain people you're following instead of everyone you're following?

**Comment by UnCrevard** [comment]
No the follow command follows everything. You can scan but it's not reliable.
