### ISSUE TITLE
Get Likes from User?

### ISSUE THREAD

**Issue by Sactorum** [UnCrevard/Younow-Tools#17]
Hi, I have seen your code and I wonder, is it capable of getting the likes of a certain stream? As in reading the likes of a certain stream from a certain user while he is streaming?

Thanks for your patience

**Comment by UnCrevard** [comment]
You can add --json switch when you're downloading a stream. It will add a json file with all the informations about the stream. Looking for the totalLikes property.

Try his.

**Comment by spinningsand** [comment]
Can doing this also give you information about the chat like show you all the chat messages that were sent?

**Comment by UnCrevard** [comment]
nope. messages are using websocket and I don't know how it works.
