### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by spinningsand** [UnCrevard/Younow-Tools#18]
Hello, I've installed this before and had to install ffmpeg to path for it to work before (after installing nodejs) and it worked just fine then. I got a new computer and installed both, then added ffmpeg to path and I get an error message saying: 

`npm ERR! network timeout at: https://registry.npmjs.org/younow-tools`

`npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\THISTHING\AppData\Roaming\npm-cache\_logs\2020-06-04T05_12_26_857Z-debug.log`

When I check the log, I get:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'younow-tools'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose npm-session cdbc7a6d3e81a493
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for younow-tools@latest network timeout at: https://registry.npmjs.org/younow-tools
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 160115ms
10 verbose type request-timeout
11 verbose stack FetchError: network timeout at: https://registry.npmjs.org/younow-tools
11 verbose stack     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:61:18)
11 verbose stack     at listOnTimeout (internal/timers.js:549:17)
11 verbose stack     at processTimers (internal/timers.js:492:7)
12 verbose cwd C:\Users\THISTHING
13 verbose Windows_NT 10.0.18363
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "younow-tools"
15 verbose node v12.18.0
16 verbose npm  v6.14.4
17 error network timeout at: https://registry.npmjs.org/younow-tools
18 verbose exit [ 1, true ]`

I'm using Windows 10. Any help would be greatly appreciated. Thanks.

**Comment by UnCrevard** [comment]
It's a NPM problem not my package. Probably the site is down of something. Wait and retry.
My package is still available.
