### ISSUE TITLE
Additional places

### ISSUE THREAD

**Issue by spinningsand** [UnCrevard/Younow-Tools#19]
Sorry if this isn't the right place to ask this, but I couldn't find anywhere to ask, but I was wondering if you could add ig live and tiktok live to the list of other sites this works on like how you already have periscope, etc. Or if there's already a way to use it at those places, how do you use it?

**Comment by UnCrevard** [comment]
Tiktok and Insta are using cookies. So you need to be logged to grab information about a stream.

Tiktok live can be shared with a link. So maybe I don't know.

**Comment by UnCrevard** [comment]
I made a new npm package to download tiktok live stream https://www.npmjs.com/package/tiktok-live

enjoy !
