### ISSUE TITLE
List recent broadcasts

### ISSUE THREAD

**Issue by lolusxd** [UnCrevard/Younow-Tools#2]
Hi, cool project so far!

But I have a little issue. I want to download just one past broadcast, not all of them so vcr isn't the way to go. I could use broadcast <broadcastId...> but I don't know the ids.

How about a function like list <users...> which gives me a list of the recent broadcast ids?
Or maybe there is already a function like this?

I would really appreciate it! Thanks!

**Comment by UnCrevard** [comment]
Hi,

Now you can use the --nodl switch to bypass the downloading.
Add -v to display broadcast id.

younow -v --nodl vcr username

Just update younow-tools and it will be available.

**Comment by lolusxd** [comment]
Works like a charm! This is excactly what I needed, thank you very much!
