### ISSUE TITLE
Searching for moments

### ISSUE THREAD

**Issue by spinningsand** [UnCrevard/Younow-Tools#20]
I was wondering if there was a way you could find all moments made of a broadcaster even if they're no on their profile page. Because sometimes they're deleted/disappear from the profile page of broadcaster, but still exist on profile page of the one who took the moment. And I believe you can also download the entire broadcast if you vcr the profile of the one who took the moment, right?

**Comment by UnCrevard** [comment]
I'm not parsing the web page. I directly use the API.
