### ISSUE TITLE
Younow-Tools is broken...

### ISSUE THREAD

**Issue by UnCrevard** [UnCrevard/Younow-Tools#3]
Younow is flash (lol) based only now. Like his ancestor BlogTV how stupid is that.

Unfortunely I don't know how to get the HLS stream anymore. The old API return nothing
({errorCode:0})

The VCR command is still working to grab some old streams.

// the problematic API
export function getPlaylist(bid): Promise<string> {
	return getURL(`${API_URL}/php/api/broadcast/videoPath/hls=1/broadcastId=${bid}`, "utf8")
}

I don't know how to fix it, cuz I can't find a way to monitor flash network request. Flash is out of process now on Firefox & Chrome.

If somebody knows the new URLS leave a comment below thanks !!!

**Comment by MathiasR91** [comment]
This is so frustrating. I loved this tool to bits. It allowed me to watch all my favorite broadcasts after work (I have two jobs). Please guys figure out a way to fix it.

**Comment by crockpoot** [comment]
Having the same problem. Refuses to download/record broadcasts now.

**Comment by UnCrevard** [comment]
now using rtmp stream. You MUST have ffmpeg in your path to make it work.

rewind of stream is now more available for live stream.
