### ISSUE TITLE
Specify user to download stream from

### ISSUE THREAD

**Issue by wiiarctus** [UnCrevard/Younow-Tools#5]
Hello, firstly I want to thank you for this project! :)
My question (or feature request if it is not possible yet) is to do something just like:
"younow user streamer123 (-t 1)" to grab a stream from younow without getting
the entire follower list of a user with "younow -t 1 follow user123" to only download
one stream at a time? :D

**Comment by wiiarctus** [comment]
I don't know really how to describe it..
I just want to get a stream when it gets live, let's say I start the command when the stream is not online, it checks e.g. every minute if it is live and when the stream is on, your program start grabbing it. When the stream wents offline and then online again the same happens and so on.. :D^^

**Comment by wiiarctus** [comment]
Is it not possible, or why are you closing this thread? :D

**Comment by donradzsk** [comment]
Where in Windows would you put follow.js and can you have multiples in one line? Like
`younow -t 1 scan follow1.js follow2.js follow3.js`

**Comment by UnCrevard** [comment]
You can only use one script. You need to merge all username like this.

if (user.profile=="username_of_the_broadcaster" ||
 user.profile=="whatever" ||
user.profile=="blablabla")
        {
            return "follow";
        }

**Comment by donradzsk** [comment]
Thanks. And "username_of_the_broadcaster" can be their userID# right (in case of name change)? And follow.js goes in the same PATH as ffmpeg?

**Comment by UnCrevard** [comment]
use user.userId==number

the script can be everywhere.
