### ISSUE TITLE
Issues with scan

### ISSUE THREAD

**Issue by chickenmango1** [UnCrevard/Younow-Tools#6]
Looks like the latest younow update is causing issues with the scan function.

**Comment by UnCrevard** [comment]
what kind of issue ?

type ` younow.cmd api`

it's working fine for me.

**Comment by chickenmango1** [comment]
it works however broadcasts are randomly dropping from the scan when the
broadcaster is still live.  Almost like the connection is being reset or
severed.

**Comment by chickenmango1** [comment]
Thanks its still happening to me.  How do I " I've fixed it by forcing
reconnection if the live is still running and download the replay at the
end."?

**Comment by chickenmango1** [comment]
I appreciate your work. How do I install your new tool? I dont see any
instructions  on github.

**Comment by chickenmango1** [comment]
I was able to install your new tool and I love the direction you are going,
however when I try to record from younow i get an error username:false.

**Comment by UnCrevard** [comment]
yes it was broken. You need to update https://github.com/UnCrevard/LiveStreamingDownloader/releases/tag/v0.2

Younow has made some change recently so some things are broken. Working on younow-tools too.

Thanks for the report.

**Comment by UnCrevard** [comment]
it happen sometimes when the stream is dead or ban but still online.
LSD is waiting for the end then try to download the replay. it works most of the time.

**Comment by chickenmango1** [comment]
what location do the recording go to? Still does not appear to be working.
 The stream is live when I receive the 246 error

**Comment by UnCrevard** [comment]
it's like younow-tools. ffmpeg aborts the recording sometimes.

246 means broadcast is still running so the replay is not yet available.

Now I wait for the end of the live to download the replay. It's working.

But I can't post it right now I can't find a solution for another bug. Stay tuned.

**Comment by UnCrevard** [comment]
btw there is a ez way to do this.

create a empty script file.

then add users to follow to the database like this : younow.cmd add username or userid

then run younow.cmd scan script.js

the scanner automatically reload database when a new user is added, so it can running all the time.

I'm just discovering my own software 😂

**Comment by chickenmango1** [comment]
I am sure you already know that younow tools no longer works as a result of
the younow updates last night, however im letting you know just in  case.
