### ISSUE TITLE
Broken :(

### ISSUE THREAD

**Issue by chickenmango1** [UnCrevard/Younow-Tools#8]
Looks like the latest content release has broken younow tools.  Thanks for everything you do.

**Comment by UnCrevard** [comment]
yes younow is not using flash anymore (good news) but they're not using hls or dash (like everybody does)

streams are now using websocket (wtf) I never heard about this crap. I hope there is no encryption also.

Younow is only compatible with chrome/vivaldi/opera.

I'm working on it but don't be in hurry... it looks like some pretty nasty vicious stuff 😭

**Comment by chickenmango1** [comment]
no hurry i have confidence in you lol

**Comment by chickenmango1** [comment]
Pretty sure they are requiring authentication to view streams now.

**Comment by donradzsk** [comment]
Is younow broken in your other tool too?

**Comment by UnCrevard** [comment]
Hi everybody !

A new version is here to bypass the last update/protection from younow.

But unfortunely is kinda hack. Now streams are downloaded ONLY after the end.
Nothing change for moments or ended broadcasts (vcr or broadcast command).

Hope to find a better way but they're using authentification & some shitty protocol.

Thanks for your feedbacks 😃
